apiVersion: v1
kind: PersistentVolume
metadata:
  name: evergreen-share-nfs
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.128.0.2
    path: "/mnt/evergreen"
