# docker-compose.yml
#
# vars defined in .env
#
services:
  web:
    build:
      context: .
      extra_hosts:
        - "public.localhost:127.0.1.2"
        - "public:127.0.1.2"
        - "private.localhost:127.0.1.3"
        - "private:127.0.1.3"
    image: '${IMAGE}'
    restart: 'no'
    hostname: '${HOST}'
    container_name: 'eg-${HOST}'
    ports:
      - '${SSL_PORT}:22'
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
      - '210:210'
      - '6001:6001'
    volumes:
      - '/mnt/evergreen:/mnt/evergreen'
